# Generated by Django 4.0 on 2023-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechTime', '0002_alter_myuser_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
