# Generated by Django 4.0 on 2023-06-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechTime', '0004_myuser_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechTime.niveau')),
            ],
        ),
    ]
