# Generated by Django 4.0 on 2023-06-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechTime', '0006_alter_myuser_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('week_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechTime.matiere')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechTime.myuser')),
            ],
        ),
    ]
