# Generated by Django 4.2.2 on 2023-06-29 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechTime', '0008_classroom_shedule_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TechTime.niveau'),
        ),
    ]
