# Generated by Django 4.2.2 on 2023-06-29 12:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechTime', '0009_shedule_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='bgColor',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
